CREATE EXTENSION IF NOT EXISTS citext;
CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  email CITEXT UNIQUE NOT NULL,
  password BYTEA NOT NULL,
  pinged BOOLEAN DEFAULT FALSE,
  last_pinged_at TIMESTAMP(0) WITH TIME ZONE,
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
  pinged_partner_count INT DEFAULT 0,
  partner_id BIGINT,
  FOREIGN KEY (partner_id) REFERENCES users(id) ON DELETE
  SET NULL DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT check_self_partner CHECK (id != partner_id)
);