CREATE TABLE IF NOT EXISTS user_invitations (
  token bytea PRIMARY KEY,
  expiry TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  user_id BIGINT UNIQUE NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)